name: fintrack
description: "Personal Finance Tracking Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # State Management (Required)
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0

  # Network & API
  dio: ^5.7.0
  dartz: ^0.10.1

  # Data Visualization
  fl_chart: ^0.69.0

  # Utilities
  intl: ^0.19.0

  # Navigation
  go_router: ^14.2.7

  # JSON Serialization
  json_annotation: ^4.9.0

  # Caching & Persistence
  hive_ce: ^2.14.0
  hive_ce_flutter: ^2.3.2
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  
  # Connectivity
  connectivity_plus: ^5.0.2

  # UI Components
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  # Linting
  flutter_lints: ^2.0.0

  # Code Generation for Hive & JSON
  build_runner: ^2.4.13
  hive_ce_generator: ^1.9.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock_data/
    - assets/mock_data/transactions.json
    - assets/mock_data/categories.json