// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fintrack/data/models/cache_metadata.dart';
import 'package:fintrack/data/models/cached_transaction.dart';
import 'package:fintrack/data/models/hive_key_value.dart';
import 'data/models/hive_models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CacheMetadataAdapter());
    registerAdapter(CachedTransactionAdapter());
    registerAdapter(HiveCategoryAdapter());
    registerAdapter(HiveKeyValueAdapter());
    registerAdapter(HiveSyncOperationAdapter());
    registerAdapter(HiveSyncQueueItemAdapter());
    registerAdapter(HiveSyncStatusAdapter());
    registerAdapter(HiveTransactionAdapter());
    registerAdapter(HiveTransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CacheMetadataAdapter());
    registerAdapter(CachedTransactionAdapter());
    registerAdapter(HiveCategoryAdapter());
    registerAdapter(HiveKeyValueAdapter());
    registerAdapter(HiveSyncOperationAdapter());
    registerAdapter(HiveSyncQueueItemAdapter());
    registerAdapter(HiveSyncStatusAdapter());
    registerAdapter(HiveTransactionAdapter());
    registerAdapter(HiveTransactionTypeAdapter());
  }
}
