// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fintrack/data/models/cache_metadata.dart';
import 'package:fintrack/data/models/cached_transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CacheMetadataAdapter());
    registerAdapter(CachedTransactionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CacheMetadataAdapter());
    registerAdapter(CachedTransactionAdapter());
  }
}
